# Generated by Django 5.0.1 on 2024-02-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('phno', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('transactions', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carname', models.CharField(max_length=20)),
                ('carprice', models.IntegerField(max_length=30)),
                ('carcondition', models.CharField(max_length=100)),
                ('carcompany', models.CharField(max_length=30)),
                ('carseating', models.IntegerField(max_length=30)),
                ('carmilaze', models.IntegerField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('phno', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('transactions', models.IntegerField(max_length=100)),
                ('vehicle', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('phno', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('transactions', models.IntegerField(max_length=100)),
                ('vehicle', models.CharField(max_length=12)),
            ],
        ),
    ]
