# Generated by Django 5.0.1 on 2024-02-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='transactions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='carmilaze',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='transactions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seller',
            name='transactions',
            field=models.IntegerField(),
        ),
    ]
