# Generated by Django 5.0.1 on 2024-02-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0002_alter_admin_transactions_alter_car_carmilaze_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='carseating',
            field=models.IntegerField(),
        ),
    ]
