# Generated by Django 5.0.1 on 2024-03-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0004_remove_car_carprice_remove_car_carseating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin_table',
        ),
        migrations.AlterModelTable(
            name='car',
            table='car_table',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer_table',
        ),
        migrations.AlterModelTable(
            name='seller',
            table='seller_table',
        ),
    ]
