# Generated by Django 5.0.1 on 2024-03-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0005_alter_admin_table_alter_car_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='carmilaze',
            new_name='carmileage',
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
