# Generated by Django 5.0.1 on 2024-03-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0008_admin_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Services', models.CharField(choices=[('car booking', 'Car Booking'), ('car driver booking', 'Car Driver Booking'), ('car renting', 'Car Renting'), ('car services', 'Car Services'), ('feedback', 'Feedback'), ('price calculator', 'Price Calculator')], max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
            ],
        ),
    ]
